from .i18n import i18n_router
from .start import start_router
from .help import help_router
from .configs.blocked import blocked_router
from .mita import mita_router
from .configs.prompt import prompt_router
from .stats import stats_router
from .reset import reset_router
from .ask import  ask_router
from .configs.voice_person import voice_person_router
from .voice import voice_router
from .configs.voice_lang import voice_lang
from .configs.is_history import is_history
from .configs.voice_mode import voicemod_router
from ..services.conditions import conditions_accept_router
from .mailing import mailing_router
from ..services.conv_timer import conv_timer_router
from .configs.set_voice_engine import set_voice_engine_router
from .configs.subscribe import subscribe_router
from .tik_tak_toe import tik_tak_toe_router
from .configs.config_voice_engine import config_voice_engine_router
from .image_generate import image_generate_router